services:
  nginx:
    build: services/nginx/.
    container_name: nginx
    volumes:
      - ./services/nginx/certs:/etc/nginx/certs:ro
      - ./app:/app
    ports:
      - "3000:443"
    depends_on:
      - auth
  
  auth:
    build: services/auth/.
    container_name: auth
    env_file:
      - services/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - auth_data:/app/data
    networks:
      - auth_network
  
  user:
    build: services/user/.
    container_name: user
    env_file:
      - services/user/.env
    ports:
      - "3002:3002"
    volumes:
      - user_data:/app/data
    networks:
      - user_network
    depends_on:
      - auth

volumes:
  auth_data:
  user_data:

networks:
  auth_network:
    driver: bridge
  user_network:
    driver: bridge