services:
  nginx:
    build: services/nginx/.
    container_name: nginx
    volumes:
      - ./services/nginx/certs:/etc/nginx/certs:ro
      - ./app:/app
    ports:
      - "3000:443"
    depends_on:
      - auth
  
  auth:
    build: services/auth/.
    container_name: auth
    env_file:
      - services/auth/.env
    volumes:
      - auth_data:/app/data

volumes:
  auth_data:
