services:
  nginx:
    build: services/nginx/.
    container_name: nginx
    volumes:
      - ./services/nginx/certs:/etc/nginx/certs:ro
      - ./app:/app
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - auth
      - user
    networks:
      - auth_network
      - user_network
    restart: unless-stopped
  
  auth:
    build: services/auth/.
    container_name: auth
    ports:
      - "3001:3001"
    env_file:
      - services/auth/.env
    volumes:
      - auth_data:/app/data
    networks:
      - auth_network
    depends_on:
      - rabbitMQ
    restart: unless-stopped
  
  user:
    build: services/user/.
    container_name: user
    env_file:
      - services/user/.env
    ports:
      - "3002:3002"
    volumes:
      - user_data:/app/data
    networks:
      - user_network
    depends_on:
      - rabbitMQ
    restart: unless-stopped
  
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitMQ
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Management UI
    # env_file:
    #   - services/rabbitMQ/.env
    networks:
      - auth_network
      - user_network
    restart: unless-stopped

volumes:
  auth_data:
  user_data:

networks:
  auth_network:
    driver: bridge
  user_network:
    driver: bridge