# POST http://localhost:3001/login
# Content-Type: application/json

# {
#   "username": "Ali",
#   "password": "123"
# }

# POST http://localhost:3001/2fa/verify
# Content-Type: application/json

# {
# 	"email": "altintoprakali98@gmail.com",
# 	"code": "461350"
# }

# DELETE http://localhost:3002/profile/delete
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBbGkiLCJlbWFpbCI6ImFsdGludG9wcmFrYWxpOThAZ21haWwuY29tIiwiaWF0IjoxNzUzMTE0MTMxLCJleHAiOjE3NTMxMTc3MzF9.gxFuz3VV71OkbyYM8WafC3fFbjNtBDdR9mmVwxU-gQA

# POST http://localhost:3001/2fa/request
# Content-Type: application/json

# {
# 	"email": "altintoprakali98@gmail.com"
# }

# POST http://localhost:3001/register
# Content-Type: application/json

# {
# 	"username": "Ali",
# 	"password": "123",
# 	"email": "altintoprakali98@gmail.com"
# }

# GET http://localhost:3002/profile?username=Ali
# Content-Type: application/json

# GET http://localhost:3002/profile/1/friends
# Content-Type: application/json

# {
# 	"friendId": "2"
# }
