# POST http://localhost:3001/login
# Content-Type: application/json

# {
#   "username": "berhan",
#   "password": "123"
# }

# POST http://localhost:3001/register
# Content-Type: application/json

# {
# 	"username": "Berhan",
# 	"password": "123"
# }

# GET http://localhost:3002/profile?username=Ahmet
# Content-Type: application/json